In [1]:
import numpy as np

## min

In [309]:
one_array = np.array([2, 4, 7, 2, 3, 1, 9])

In [312]:
min(list(one_array.flat))

TypeError: unorderable types: int() < NoneType()

In [98]:
def minimum(a):
    min = a[0]
    for element in a.flat:
        if np.all(element <= min):
            min = element
    return min        


In [99]:
minimum(one_array)

1

In [122]:
two_array = np.array([[9, 3, 5], [7, 9, 1]])

In [123]:
minimum(two_array)

1

## max

In [124]:
def maximum(a):
    max = a[0]
    for element in a.flat:
        if np.all(element >= max):
            max = element
    return max        


In [125]:
maximum(one_array)

9

In [126]:
maximum(two_array)

9

## mean

In [169]:
def mean(a):
    sum = 0
    count = 0
    if a.ndim == 1:
        
        for x in a:
            count += 1
            sum += x
        return sum/count
    elif a.ndim == 2:
        for row in a:
            for col in row:
                count += 1
                sum += col
        return sum/count       
            
        

In [170]:
mean(one_array)

4.0

In [171]:
mean(two_array)

5.666666666666667

## argmin

In [153]:
def argminimum(a):
    if a.ndim == 2:
        index = 0
        i = -1
        min = a[0, 0]
        crow = -1
        ccol = -1
        for row in a:
            crow += 1
            ccol = -1
            
            for col in row:
                ccol +=1
                if min >= col:
                    min = col
                    index = (crow, ccol)
        return index  
    
    elif a.ndim == 1:
        min = a[0]
        index = 0
        i = -1
        for element in a:   
            i +=1
            if element <= min:
                min = element
                index = i
            
        return 'index', index


In [154]:
argminimum(one_array)

('index', 5)

In [155]:
argminimum(two_array)

(1, 2)

## argmax

In [150]:
def argmaximum(a):
    if a.ndim == 2:
        index = 0
        i = -1
        max = a[0, 0]
        crow = -1
        ccol = -1
        for row in a:
            crow += 1
            ccol = -1
            
            for col in row:
                ccol +=1
                if max <= col:
                    max = col
                    index = (crow, ccol)
        return index  
    
    elif a.ndim == 1:
        max = a[0]
        index = 0
        i = -1
        for element in a:   
            i +=1
            if element >= max:
                max = element
                index = i
            
        return 'index', index


In [151]:
argmaximum(one_array)

('index', 6)

In [152]:
argmaximum(two_array)

(1, 1)

## flat

In [198]:
def flatten(a, style = 'C'):
    result = list()
    index = 0
    if a.ndim == 1:
        return a
    if a.ndim == 2:
        
        if style == 'C':
            for row in a:
                for col in row:
                    result.append(col)
            
            return result        
        elif style == 'F':
            row, col = a.shape
            for y in range(col):
                for x in range(row):
                    result.append(a[x, y])

            return result        
        
                


In [199]:
flatten(one_array)

array([2, 4, 7, 2, 3, 1, 9])

In [200]:
flatten(two_array, 'F')

[9, 7, 3, 9, 5, 1]

## ravel

In [201]:
def ravel(a):
    return flatten(a)

In [202]:
ravel(one_array)

array([2, 4, 7, 2, 3, 1, 9])

In [203]:
ravel(two_array)

[9, 3, 5, 7, 9, 1]

## Element-wise multiplication

In [224]:
def multiply_arrays(c, d):
    a = np.array(c)
    b = np.array(d)
    final_list = list()
    if a.ndim == 1:
        if len(a) != len(b):
            return 'Shape of both arrays should be same'
        else:
            
            for x, y  in zip(a, b):
                final_list.append(x*y)
            return final_list    
    
    elif a.ndim == 2:
        x, y = a.shape
        if a.shape != b.shape:
            return 'Shape of both arrays should be same'

        for xx in range(x):
            sublist = []
            for yy in range(y):
                sublist.append(a[xx, yy]*b[xx, yy])
            final_list.append(sublist)
        return final_list    
                
        
                

In [313]:
x = np.array([[4, 1, 1], [2, 4, 1]])
multiply_arrays(x, two_array)

[[36, 3, 5], [14, 36, 1]]

In [226]:
multiply_arrays([1, 2], [3, 4])

[3, 8]

## arange followed by reshape

In [305]:
def reshape(alist, shape):
    final = []
    x = shape[0]
    y = shape[1]
    index = 0    
    for i in range(x):
        sublist = []
        for j in range(y):
            sublist.append(alist[index])
            index += 1
        final.append(sublist)
    return final    
    

In [239]:
def arange_reshape(num, shape):
    alist = []
    final = []
    x = shape[0]
    y = shape[1]
    for i in range(num):
        alist.append(i)
    index = 0    
    for i in range(x):
        sublist = []
        for j in range(y):
            sublist.append(alist[index])
            index += 1
        final.append(sublist)
    return final    
            

In [241]:
arange_reshape(12, (6,2))

[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]

## Identity matrix

In [242]:
def identity(shape):
    final = []
    for x in range(shape):
        sublist = []
        for y in range(shape):
            if x == y:
                sublist.append(1)
            else:
                sublist.append(0)
        final.append(sublist)
    return final    
            
            

In [246]:
identity(4)

[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]

In [245]:
identity(1)

[[1]]

##  Sum

In [247]:
def sum(b):
    a = np.array(b)
    sum = 0
    if a.ndim == 1:
        
        for x in a:
            sum += x
        return sum
    elif a.ndim == 2:
        for row in a:
            
            for col in row:
                sum += col
        return sum      


In [248]:
sum([1, 2, 3, 4])

10

In [249]:
sum([[1, 2], [3, 4]])

10

In [250]:
sum(one_array)

28

In [251]:
sum(two_array)

34

## Diagonal elements

In [255]:
def diag(arr):
    final = []
    a = np.array(arr)
    if a.ndim == 1:
        shape = len(a)
        index = 0
        for i in range(shape):
            sublist = []
            for j in range(shape):
                if i == j:
                    sublist.append(a[index])
                    index += 1
                else:
                    sublist.append(0)
            final.append(sublist)
        return final
    
    elif a.ndim == 2:
        x, y = a.shape
        for i in range(x):
            for j in range(y):
                if i == j:
                    final.append(a[i, j])
        return final            
                    
    
                    
                    
                    
                
    
    

In [256]:
diag([1, 2, 3, 4])

[[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]]

In [258]:
diag([[1, 2], [3, 4]])

[1, 4]

## tril

In [263]:
def tril(arr):
    a = np.array(arr)
    x, y = a.shape
    for i in range(x):
        for j in range(y):
            if i < j:
                a[i, j]=0
    return a            
                

In [264]:
tril([[1, 2, 3], [4, 5, 6]])

array([[1, 0, 0],
       [4, 5, 0]])

## triu

In [266]:
def triu(arr):
    a = np.array(arr)
    x, y = a.shape
    for i in range(x):
        for j in range(y):
            if i > j:
                a[i, j]=0
    return a            


In [267]:
triu([[3, 4], [5, 6]])

array([[3, 4],
       [0, 6]])

## Dot Product

In [306]:
def dot(arr1, arr2):
    alist = []
    sum = 0
    A = np.array(arr1)
    B = np.array(arr2)
    if A.ndim == 1:
        A = np.array([A])
        
    if B.ndim == 1:
        B = np.array([B])    
        
        
    if A.shape[1] == B.shape[0]:
        for x in A:
            for y in B.T:
                sum = 0
                for i, j in zip(x, y):
                    sum += i*j  
                alist.append(sum)
        return reshape(alist, (A.shape[0], B.shape[1]))        
                
    

In [307]:
dot([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )

[[30, 36, 42], [66, 81, 96], [102, 126, 150]]

In [318]:
np.zeros((3,))

array([ 0.,  0.,  0.])