## Numpy 

In [153]:
import numpy as np

In [36]:
a = np.arange(15).reshape((3,5))

In [37]:
a.shape

(3, 5)

In [10]:
#no. of dimensions 
a.ndim

2

In [11]:
a.dtype

dtype('int64')

In [14]:
a.dtype.itemsize             # or a.itemsize

8

In [15]:
type(a)

numpy.ndarray

In [16]:
b=np.array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

In [61]:
c=np.array([[2,3,4], [5,6, 9]])
c.shape

(2, 3)

In [63]:
c.shape = (3, 2)

In [64]:
c

array([[2, 3],
       [4, 5],
       [6, 9]])

In [40]:
d = np.zeros((2,3))

In [44]:
d.dtype

dtype('float64')

In [48]:
np.arange(1,10,0.3)              #last arg is steps

array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ,
        4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,  7. ,  7.3,
        7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7])

In [52]:
np.linspace(1,10,100)            #last arg is no. of elements

array([  1.        ,   1.09090909,   1.18181818,   1.27272727,
         1.36363636,   1.45454545,   1.54545455,   1.63636364,
         1.72727273,   1.81818182,   1.90909091,   2.        ,
         2.09090909,   2.18181818,   2.27272727,   2.36363636,
         2.45454545,   2.54545455,   2.63636364,   2.72727273,
         2.81818182,   2.90909091,   3.        ,   3.09090909,
         3.18181818,   3.27272727,   3.36363636,   3.45454545,
         3.54545455,   3.63636364,   3.72727273,   3.81818182,
         3.90909091,   4.        ,   4.09090909,   4.18181818,
         4.27272727,   4.36363636,   4.45454545,   4.54545455,
         4.63636364,   4.72727273,   4.81818182,   4.90909091,
         5.        ,   5.09090909,   5.18181818,   5.27272727,
         5.36363636,   5.45454545,   5.54545455,   5.63636364,
         5.72727273,   5.81818182,   5.90909091,   6.        ,
         6.09090909,   6.18181818,   6.27272727,   6.36363636,
         6.45454545,   6.54545455,   6.63636364,   6.72

In [54]:
a.dtype.name

'int64'

In [212]:
def f(x,y):
     return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)   #fromfunction is a generator takes index of each cell 


In [213]:
b[2,3]

23

In [214]:
for x in b:
    print(x)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [215]:
for x in b.flat:
    print(x)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [219]:
c = np.floor(10 * np.random.random((3,4)))

In [93]:
c.ravel()              #flattens out the array

array([ 0.,  5.,  9.,  7.,  5.,  1.,  0.,  3.,  8.,  9.,  9.,  8.])

In [96]:
c.reshape((6,2))       #doesn't modify original array

array([[ 0.,  5.],
       [ 9.,  7.],
       [ 5.,  1.],
       [ 0.,  3.],
       [ 8.,  9.],
       [ 9.,  8.]])

In [220]:
c

array([[ 8.,  0.,  0.,  7.],
       [ 8.,  9.,  5.,  2.],
       [ 0.,  3.,  3.,  2.]])

In [221]:
c.min(axis=1)

array([ 0.,  2.,  0.])

In [222]:
c.max(axis=0)

array([ 8.,  9.,  5.,  7.])

In [100]:
c.resize((6,2))           #modifies original array

In [101]:
c

array([[ 0.,  5.],
       [ 9.,  7.],
       [ 5.,  1.],
       [ 0.,  3.],
       [ 8.,  9.],
       [ 9.,  8.]])

In [107]:
c.reshape(-1,6)        #inplace of -1 it calculates the dimension itself

array([[ 2.,  5.,  7.,  0.,  6.,  4.],
       [ 0.,  8.,  5.,  6.,  1.,  9.]])

In [127]:
a=np.zeros((2,2))
b=np.ones((2,3))

In [128]:
np.hstack((a, b))    #row index of both arrays should be same

array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.]])

In [142]:
a=np.zeros((2, 2))
b=np.ones((3, 2))

In [143]:
np.vstack((a, b))    #column index of both arrays should be same

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [144]:
a=[1,2]
b=[3,4]

In [145]:
np.column_stack((a, b))

array([[1, 3],
       [2, 4]])

In [280]:
z = np.array([4.,2.])

In [284]:
z[:,newaxis]

array([[ 4.],
       [ 2.]])

In [282]:
a = np.floor(10*np.random.random((6,12)))
a

array([[ 8.,  0.,  3.,  4.,  8.,  9.,  6.,  1.,  6.,  6.,  7.,  7.],
       [ 8.,  7.,  5.,  0.,  5.,  2.,  2.,  3.,  7.,  5.,  6.,  1.],
       [ 4.,  2.,  3.,  8.,  9.,  3.,  6.,  1.,  6.,  0.,  2.,  4.],
       [ 2.,  4.,  4.,  0.,  9.,  2.,  5.,  2.,  8.,  0.,  5.,  7.],
       [ 1.,  9.,  1.,  6.,  2.,  6.,  0.,  4.,  5.,  8.,  5.,  9.],
       [ 2.,  2.,  0.,  9.,  7.,  6.,  3.,  2.,  2.,  3.,  7.,  7.]])

In [166]:
np.hsplit(a, 4)       #splits array into 4 equal horizontal parts
                      #array shud be split equally by the specified number

[array([[ 6.,  1.,  1.],
        [ 9.,  9.,  2.],
        [ 6.,  4.,  6.],
        [ 4.,  0.,  9.],
        [ 4.,  8.,  7.]]), array([[ 7.,  1.,  7.],
        [ 1.,  2.,  7.],
        [ 1.,  5.,  9.],
        [ 0.,  5.,  5.],
        [ 6.,  0.,  4.]]), array([[ 5.,  3.,  6.],
        [ 7.,  5.,  8.],
        [ 7.,  1.,  0.],
        [ 9.,  4.,  1.],
        [ 7.,  1.,  5.]]), array([[ 1.,  4.,  6.],
        [ 8.,  7.,  5.],
        [ 4.,  4.,  3.],
        [ 0.,  7.,  9.],
        [ 5.,  2.,  5.]])]

In [171]:
np.vsplit(a, 3)

[array([[ 2.,  0.,  4.,  5.,  9.,  5.,  6.,  4.,  1.,  3.,  4.,  4.],
        [ 1.,  6.,  9.,  2.,  7.,  3.,  2.,  0.,  3.,  6.,  3.,  8.]]),
 array([[ 2.,  6.,  4.,  7.,  1.,  7.,  7.,  8.,  0.,  5.,  5.,  8.],
        [ 3.,  6.,  2.,  2.,  5.,  9.,  3.,  7.,  8.,  2.,  8.,  2.]]),
 array([[ 5.,  5.,  4.,  7.,  4.,  5.,  0.,  2.,  1.,  8.,  0.,  1.],
        [ 3.,  3.,  3.,  4.,  2.,  7.,  4.,  0.,  2.,  8.,  0.,  5.]])]

In [177]:
np.array_split(a,4)   #splits array into specified parts even if parts are unequal

[array([[ 2.,  0.,  4.,  5.,  9.,  5.,  6.,  4.,  1.,  3.,  4.,  4.],
        [ 1.,  6.,  9.,  2.,  7.,  3.,  2.,  0.,  3.,  6.,  3.,  8.]]),
 array([[ 2.,  6.,  4.,  7.,  1.,  7.,  7.,  8.,  0.,  5.,  5.,  8.],
        [ 3.,  6.,  2.,  2.,  5.,  9.,  3.,  7.,  8.,  2.,  8.,  2.]]),
 array([[ 5.,  5.,  4.,  7.,  4.,  5.,  0.,  2.,  1.,  8.,  0.,  1.]]),
 array([[ 3.,  3.,  3.,  4.,  2.,  7.,  4.,  0.,  2.,  8.,  0.,  5.]])]

In [178]:
a

array([[ 2.,  0.,  4.,  5.,  9.,  5.,  6.,  4.,  1.,  3.,  4.,  4.],
       [ 1.,  6.,  9.,  2.,  7.,  3.,  2.,  0.,  3.,  6.,  3.,  8.],
       [ 2.,  6.,  4.,  7.,  1.,  7.,  7.,  8.,  0.,  5.,  5.,  8.],
       [ 3.,  6.,  2.,  2.,  5.,  9.,  3.,  7.,  8.,  2.,  8.,  2.],
       [ 5.,  5.,  4.,  7.,  4.,  5.,  0.,  2.,  1.,  8.,  0.,  1.],
       [ 3.,  3.,  3.,  4.,  2.,  7.,  4.,  0.,  2.,  8.,  0.,  5.]])

In [180]:
c

array([[ 2.,  5.,  7.,  0.],
       [ 6.,  4.,  0.,  8.],
       [ 5.,  6.,  1.,  9.]])

In [187]:
d = c.view()    #creates a view of c , c and a are diff objects but share same data

In [188]:
d[2, 3] = 12 

In [191]:
c

array([[  2.,   5.,   7.,   0.],
       [  6.,   4.,   0.,   8.],
       [  5.,   6.,   1.,  12.]])

In [198]:
x = np.arange(12)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [200]:
x[3]

9

In [201]:
c

array([[  2.,   5.,   7.,   0.],
       [  6.,   4.,   0.,   8.],
       [  5.,   6.,   1.,  12.]])

In [205]:
c.argmax(axis=1)

array([2, 3, 3])

In [223]:
c.argmin(axis=1)

array([1, 3, 0])

In [206]:
c.shape

(3, 4)

In [207]:
c

array([[  2.,   5.,   7.,   0.],
       [  6.,   4.,   0.,   8.],
       [  5.,   6.,   1.,  12.]])

In [210]:
for x in c.flat:
    print(x)

2.0
5.0
7.0
0.0
6.0
4.0
0.0
8.0
5.0
6.0
1.0
12.0


In [224]:
a

array([[ 2.,  0.,  4.,  5.,  9.,  5.,  6.,  4.,  1.,  3.,  4.,  4.],
       [ 1.,  6.,  9.,  2.,  7.,  3.,  2.,  0.,  3.,  6.,  3.,  8.],
       [ 2.,  6.,  4.,  7.,  1.,  7.,  7.,  8.,  0.,  5.,  5.,  8.],
       [ 3.,  6.,  2.,  2.,  5.,  9.,  3.,  7.,  8.,  2.,  8.,  2.],
       [ 5.,  5.,  4.,  7.,  4.,  5.,  0.,  2.,  1.,  8.,  0.,  1.],
       [ 3.,  3.,  3.,  4.,  2.,  7.,  4.,  0.,  2.,  8.,  0.,  5.]])

In [225]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [227]:
c

array([[ 8.,  0.,  0.,  7.],
       [ 8.,  9.,  5.,  2.],
       [ 0.,  3.,  3.,  2.]])

In [229]:
a = np.arange(15).reshape((3,5))

In [232]:
b = np.random.random((5,5))

In [233]:
a.dot(b)

array([[  2.43223829,   5.84773774,   7.2935205 ,   3.61667459,   7.7121809 ],
       [ 11.4554499 ,  18.54274187,  23.45278573,  12.77345712,
         24.65588501],
       [ 20.47866151,  31.23774599,  39.61205095,  21.93023965,
         41.59958911]])

In [235]:
c = np.random.random((3,5))
a * c 

array([[ 0.        ,  0.30075286,  1.15056803,  2.82110917,  0.56693825],
       [ 3.70641195,  1.14295564,  3.02567723,  6.69509092,  4.27554241],
       [ 6.16296335,  0.21995748,  6.56093873,  2.86025261,  8.25598961]])

In [239]:
new = np.eye(4)           #identity matrix

In [240]:
new

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [242]:
new.trace()

4.0

In [245]:
np.diag(new)            #return diagonal elements of an array

array([ 1.,  1.,  1.,  1.])

In [249]:
np.diag([1, 2, 3, 4], k=1)   #constructs an array with given diagonal elements 
                             #k is diagonal number

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [251]:
np.diag([1, 2, 3, 4], k=-5)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0]])

In [252]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [253]:
np.sum(a)

105

In [255]:
np.sum(a, axis = 0)

array([15, 18, 21, 24, 27])

In [258]:
np.mean(a)

7.0

In [261]:
np.mean(a, axis=1)

array([  2.,   7.,  12.])

In [263]:
np.empty((3,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [265]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [266]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [285]:
a = np.array([, 2])
b = np.array([3, 4])

In [286]:
a * b

array([3, 8])

In [287]:
ax, bx = np.ix_(a, b)

In [288]:
ax

array([[1],
       [2]])

In [289]:
bx

array([[3, 4]])

In [290]:
ax * bx

array([[3, 4],
       [6, 8]])

In [291]:
c = np.array([1, 2, 3])

In [292]:
ax, cx = np.ix_(a, c)

In [293]:
cx

array([[1, 2, 3]])

In [294]:
ax

array([[1],
       [2]])

In [295]:
a = np.array([[1, 0, 3], [5, 4, 0], [0, 0, 3]])

In [297]:
np.nonzero(a)                # returns index of non-zero elements

(array([0, 0, 1, 1, 2]), array([0, 2, 0, 1, 2]))

In [299]:
a = np.arange(4).reshape(2,2); 

In [301]:
a.diagonal()


array([0, 3])

In [314]:
a = np.arange(4).reshape(2,2); a

array([[0, 1],
       [2, 3]])

In [313]:
a.diagonal(1, 0)

array([[2],
       [3]])

In [315]:
b = np.array([[4, 9], [3, 5]])

In [321]:
a = np.arange(27).reshape(3, 3, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [322]:
a.diagonal()

array([[ 0, 12, 24],
       [ 1, 13, 25],
       [ 2, 14, 26]])

In [325]:
a.diagonal(0, 1, 0)

array([[ 0, 12, 24],
       [ 1, 13, 25],
       [ 2, 14, 26]])

In [340]:
a.diagonal(0, 1, 2)

array([[ 0,  4,  8],
       [ 9, 13, 17],
       [18, 22, 26]])

In [344]:
b = np.array([[4, 9], [3, 5]])
b

array([[4, 9],
       [3, 5]])

In [356]:
b.diagonal(-2)

array([], dtype=int64)

In [359]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [360]:
np.ma.arange(5)

masked_array(data = [0 1 2 3 4],
             mask = False,
       fill_value = 999999)

In [363]:
np.std(a, axis=0)

array([ 1.,  1.])

In [365]:
b.flatten()

array([5, 6])

## Identity matrix 

In [366]:
def identity(shape):
    final = []
    for x in range(shape):
        sublist = []
        for y in range(shape):
            if x == y:
                sublist.append(1)
            else:
                sublist.append(0)
        final.append(sublist)
    return final    
            
            

In [367]:
identity(3)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [368]:
identity(1)

[[1]]

In [371]:
np.diag([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [374]:
np.tril([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

In [393]:
a = np.array([2, 2])

In [394]:
a

array([2, 2])

In [395]:
a.ndim

1

In [396]:
a = np.array([a])

In [392]:
a.ndim

2

In [397]:
a.shape

(1, 2)

In [398]:
a

array([[2, 2]])

In [399]:
a.T

array([[2],
       [2]])

In [400]:
a

array([[2, 2]])